ignore:
  - src/ai/backend/runner
  - src/ai/backend/kernel
coverage:
  status:
    project:
      default:
        threshold: 5%
        paths: src
    patch:
      default:
        threshold: 5%
        paths: src
